### ISSUE TITLE
request: export to GBDK

### ISSUE THREAD

**Issue by retroarch-girl** [bbbbbr/gimp-tilemap-gb#10]
Hi

Is it possible you can add the option to export to GBDK .C files, so we can rezlly use GIMP in combination with GBDK?
Since you already have code , maybe it's not much to do this?

It would be useful so people can useGIMP on all platforme when they work with GBDK.
Another reason is that there is no other GIMP plugin to do this :(

**Comment by bbbbbr** [comment]
Hello,

The recommended pathway to use GIMP with GBDK is as mentioned in the other topic #9:
GIMP -> export to PNG image -> GBDK's `png2asset` -> GBDK

I have used this process many times without issue.

While this software has useful capabilities, it is mostly "use as-is" since I do not have much capacity to provide technical support for it.
